# @name get-prompts

GET http://localhost:3333/prompts

###

# @name upload

POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="frasesPicaPau.mp3"
Content-Type: audio/mpeg

< ./frasesPicaPau.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription

POST http://localhost:3333/videos/efc96869-2fe7-47de-8c14-2004cfe6b34f/transcription
Content-Type: application/json

{
    "prompt": "Frases Pica-Pau"
}

###

# @name generate-ai-completion

POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "efc96869-2fe7-47de-8c14-2004cfe6b34f",
    "temperature": 0.5,
    "template": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}